# Generated by Django 4.0 on 2022-01-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Principal_Amount', models.CharField(max_length=11)),
                ('Intrest_Rate', models.CharField(max_length=5)),
                ('Given_Intrest', models.CharField(max_length=8)),
                ('Given_Principle', models.CharField(max_length=11)),
                ('Pending_Intrest', models.CharField(max_length=8)),
                ('Balance_Principle_Amount', models.CharField(max_length=11)),
                ('Case_N0', models.CharField(max_length=50)),
                ('Case_Type', models.CharField(max_length=10)),
                ('Case_link', models.CharField(max_length=200)),
#                 ('Person_Photo', models.ImageField(upload_to='pics')),
#                 ('Pic_promissory_note', models.ImageField(upload_to='pics')),
#                 ('Pic_Id_Proof', models.ImageField(upload_to='pics')),
#                 ('pic_Cheque', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
